# Site settings
title: Zetajs
subtitle: Web Framework
logo: /img/logo.svg
favicon: /img/logo.svg
description: > # this means to ignore newlines until "baseurl:"
 Zeta is a simple, fast, and very extendable Web Framework in Nodejs.

 Help you to Write your node web app in an angular and unexpress way.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zetajs.io" # the base hostname & protocol for your site


permalink: /post/:year/:month/:day/:title.html
paginate: 1
paginate_path: blog/page:num
github: https://github.com/BenBBear/Zeta/
footer_github: https://github.com/BenBBear/Zeta/tree/gh-pages


# Build settings
markdown: kramdown
collections:
  guide:
    output: true
    permalink: /guide/:path.html




gems:
  - jekyll-sitemap
