#
# Jekyll configurations
#

url:

baseurl: ""

highlighter: pygments
permalink: /:title/
sass:
  style: :compressed
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
